apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: rng
  name: rng
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rng
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rng
    spec:
      containers:
      - image: 172.17.0.222:5000/rng:v0.1
        imagePullPolicy: IfNotPresent
        name: rng
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
