apiVersion: v1
kind: ConfigMap
metadata:
  name: docker
  namespace: weavek8sops
data:
  daemon.json: |
    {
      "log-driver": "json-file",
      "log-opts": {
        "max-size": "100m"
      },
      "exec-opts": [
        "native.cgroupdriver=cgroupfs"
      ],
      "insecure-registries" : [
<<<<<<< HEAD
<<<<<<< HEAD
        "172.17.0.222:5000"
      ]
=======
	"172.17.0.222:5000"
      ]	
>>>>>>> Edit docker-config
=======
        "172.17.0.222:5000"
      ]
>>>>>>> fix error
    }
