apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
<<<<<<< HEAD
      - 172.17.0.200-172.17.0.250
=======
      - 172.17.0.200-172.17.0.250
>>>>>>> Add metallb
