apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: team24-backend
  name: team24-backend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: team24-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: team24-backend
    spec:
      containers:
      - image: toeikanta/flight-booking-backend:v0.3
        imagePullPolicy: IfNotPresent
        name: flight-booking-backend
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
