apiVersion: apps/v1
kind: Deployment
metadata:
   labels:
    app: web1
  name: web1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web1
   template:
    metadata:
           labels:
        app: web1
    spec:
      containers:
      - image: nginx
        name: nginx
